package com.ot.pigmy.dto;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Pattern;

import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.annotation.JsonIgnore;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Admin {

	@Id
	@GenericGenerator(name = "sequence_admin_id", strategy = "com.ot.pigmy.dto.AdminIdGenerator")
	@GeneratedValue(generator = "sequence_admin_id")
	@ApiModelProperty(value = "AutoGenerated")
	private String id;

	@NotBlank(message = "Please Enter The Admin-Name")
	@ApiModelProperty(required = true)
	private String adminName;

	@Column(unique = true)
	@NotBlank(message = "Please Enter The Admin-Email")
	@Pattern(regexp = "^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$", message = "Enter a Valid User-Email")
	@ApiModelProperty(required = true)
	private String email;

	@Column(unique = true)
	@NotBlank(message = "Please Enter The Admin-PhoneNumber")
	@ApiModelProperty(required = true)
	@Pattern(regexp = "^[6-9]{1}[0-9]{9}+$", message = "Enter Proper User-PhoneNumber")
	private String phone;

	@NotBlank(message = "Please Enter the Admin-Password")
	@ApiModelProperty(required = true)
	@Pattern(regexp = "((?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%!]).{6,15})", message = "Enter Proper Admin-Password "
			+ "\n" + " The User-Password Should Have Atleast " + "\n" + " 1 Upper Case " + "\n" + " 1 Lower Case "
			+ "\n" + " 1 Special Character " + "\n" + " And 1 Numric Character " + "\n"
			+ " The Length OF The Password Must Be Minimum OF 6 Character And Maximum OF 15 Character ")
	private String password;

	@NotBlank(message = "Please Enter the Admin-Address")
	@ApiModelProperty(required = true)
	private String address;

	private String adminProfilePic;

	@JsonIgnore
	private int otp;

	@JsonIgnore
	private String uuid;

}