package com.ot.pigmy.dto;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

import io.swagger.annotations.ApiModelProperty;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
public class CustomerAccount {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@ApiModelProperty(value = "AutoGenerated")
	private long id;

	@Column(unique = true)
	@NotNull
	@ApiModelProperty(required = true)
	private long accountNumber;

	@NotBlank
	@ApiModelProperty(required = true)
	private String accountType;

	@ApiModelProperty(required = true)
	@Getter(value = AccessLevel.NONE)
	@Setter(value = AccessLevel.NONE)
	private double balance;

	@JsonGetter
	public double getBalance() {
		return balance;
	}

	@JsonSetter
	public void setBalance(double balance) {
		this.balance = balance;
	}

	@ManyToOne
	@JsonBackReference("tax")
	@JoinColumn
	private Customer customer;

}
