package com.ot.pigmy.dto;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonSetter;

import io.swagger.annotations.ApiModelProperty;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
public class Customer {

	@Id
	@GenericGenerator(name = "sequence_customer_id", strategy = "com.ot.pigmy.dto.CustomerIdGenerator")
	@GeneratedValue(generator = "sequence_customer_id")
	@ApiModelProperty(value = "AutoGenerated")
	private String id;

	@NotBlank(message = "Please Enter The Customer-Name")
	@ApiModelProperty(required = true)
	private String customerName;

	@NotNull(message = "Please Enter The Customer-Age")
	@ApiModelProperty(required = true)
	private int age;

	@NotBlank(message = "Please Enter The Customer-Gender")
	@ApiModelProperty(required = true)
	private String gender;

	@ApiModelProperty(required = true)
	private LocalDate joiningTime;

	@UpdateTimestamp
	private LocalDateTime updatedTime;

	@Column(unique = true)
	@NotBlank(message = "Please Enter The Customer-PhoneNumber")
	@ApiModelProperty(required = true)
	@Pattern(regexp = "^[6-9]{1}[0-9]{9}+$", message = "Enter Proper Customer-PhoneNumber")
	private String phone;

	@Column(unique = true)
	@Pattern(regexp = "^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$", message = "Enter a Valid Customer-Email")
	private String email;

	@NotBlank(message = "Please Enter The Address")
	@ApiModelProperty(required = true)
	private String address;

	@Getter(value = AccessLevel.NONE)
	@Setter(value = AccessLevel.NONE)
	private String agentId;

	@JsonGetter
	public String getAgentId() {
		return agentId;
	}

	@JsonSetter
	public void setAgentId(String agentId) {
		this.agentId = agentId;
	}

	@ApiModelProperty(required = true)
	@Getter(value = AccessLevel.NONE)
	@Setter(value = AccessLevel.NONE)
	private String customerUniqueCode;

	@JsonGetter
	public String getCustomerUniqueCode() {
		return customerUniqueCode;
	}

	@JsonIgnore
	public void setCustomerUniqueCode(String customerUniqueCode) {
		this.customerUniqueCode = customerUniqueCode;
	}
	
	@Column(unique = true)
	@NotNull(message = "Please Enter the Customer-Aadhaar_Number")
	@Pattern(regexp = "^[0-9]{12}+$", message = "Enter Proper Customer-Aadhaar_Number")
	@ApiModelProperty(required = true)
	private String aadhaarNumber;

	private String customerAadharImage;
	
	private String customerProfilePic;

	@OneToMany(mappedBy = "customer", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	@JsonManagedReference("tax")
	private List<CustomerAccount> customerAccount;

}